### PR TITLE
Two typos in YEAR

### PR DESCRIPTION
**Pull request by sbunify**

### CODE REVIEW

**Comment by zmanion** [comment]
I think 2016 IDs should be moved to the 2016 csv file? And shouldn't the assignment/public dates change too? @lcashdol?

**Comment by sbunify** [comment]
Yep, I thought of this too, initially. But when looking at the artifacts, the urls for at least the first issue point to disclosures that happened back in 2015, so it's more likely just a typo...

**Comment by lcashdol** [comment]
Yep, that makes sense.

**Comment by zmanion** [comment]
I misread the commit, didn't notice it was the 2015 csv file, so just ignore my initial comment.

**Pull request merged**
